apiVersion: apps/v1

kind: Deployment

metadata:
    name: plasma
    labels:
        app: plasma

spec:
    selector:
        matchLabels:
            app: plasma
    replicas: 1

    template:
        metadata:
            labels:
                app: plasma

        spec:
            containers:
                - name: plasma

                  image: icr.io/plasma_ibm/plasma

                  imagePullPolicy: Always

                  ports:
                      - containerPort: 5000
                  env:
                      - name: DISABLE_WEB_APP
                        value: "false"